## NumPy array operation


In [5]:
import numpy as np


In [6]:
arr=np.array([1,2,3,4,5])
print(arr)
print("individual elements of the array:",arr[0])
print("basic slicing:",arr[1:4])
print("negative indexing:",arr[-4:-1])
print("step slicing:",arr[0:5:2])

[1 2 3 4 5]
individual elements of the array: 1
basic slicing: [2 3 4]
negative indexing: [2 3 4]
step slicing: [1 3 5]


In [7]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print("accessing element at row 1 and column 2:",arr_2d[0,1])
print("slicing rows 1 to 2 and columns 0 to 1:",arr_2d[0:2,0:2])
print("accessing row:",arr_2d[2])
print("accessing column:",arr_2d[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
accessing element at row 1 and column 2: 2
slicing rows 1 to 2 and columns 0 to 1: [[1 2]
 [4 5]]
accessing row: [7 8 9]
accessing column: [2 5 8]


In [8]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_arr = np.sort(unsorted)
print("unsorted array:", unsorted)
print("sorted array:", sorted_arr)

unsorted array: [3 1 4 1 5 9 2 6 5]
sorted array: [1 1 2 3 4 5 5 6 9]


##filter

In [9]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4,5])
print(arr)
odd_numbers=arr[arr%2!=0]
print("odd numbers:", odd_numbers)

[1 2 3 4 5]
odd numbers: [1 3 5]


##filterwithmask

In [11]:
mask=arr>3
print("mask for elements greater than 3:", mask) 
filtered_arr=arr[mask]
print("filtered array (elements greater than 3):", filtered_arr)    

mask for elements greater than 3: [False False False  True  True]
filtered array (elements greater than 3): [4 5]
