## numpy array operation 


In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print("basic slice ;",arr[2:4])
print("slicing with step:",arr[0:5:2])
print("negative slicing:",arr[-4:-1])

basic slice ; [3 4]
slicing with step: [1 3 5]
negative slicing: [2 3 4]


In [3]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2d array element :",arr_2d[1,2])
print("2d array row only:",arr_2d[1])
print("2d array column only:",arr_2d[:,1])

2d array element : 6
2d array row only: [4 5 6]
2d array column only: [2 5 8]


## sorting 

In [5]:
unsorted=np.array([3,4,5,2,1])
print("sorted array :",np.sort(unsorted))
arr_2d=np.array([[1,6,3],[5,6,4],[7,2,9]])
print("sorted 2d array with column wise:",np.sort(arr_2d,axis=0))
print("sorted 2d array with row wise:",np.sort(arr_2d,axis=1))

sorted array : [1 2 3 4 5]
sorted 2d array with column wise: [[1 2 3]
 [5 6 4]
 [7 6 9]]
sorted 2d array with row wise: [[1 3 6]
 [4 5 6]
 [2 7 9]]


##filter


In [2]:
import numpy as np

## adding and removing element 

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
d=a+b+c
print("sum of 3 arrays:",d)
e=np.concatenate((a,b,c))
print("concatenated array:",e)

sum of 3 arrays: [12 15 18]
concatenated array: [1 2 3 4 5 6 7 8 9]


In [7]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10,12])
c=np.array([11,12,13,14,15])
print("these are compatible",a.shape==b.shape==c.shape)

these are compatible False


In [12]:
original=np.array([[1,2,3],[4,5,6],[7,8,9]])
new_row=np.array([[10,11,12]])
with_new_row=np.vstack((original,new_row))
print("new array after adding new row:",with_new_row)
print("original array remains unchanged:",original)

new_col=np.array([[13],[14],[15]])
with_col=np.hstack((original,new_col))
print("new array after adding new column:",with_col)

new array after adding new row: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
original array remains unchanged: [[1 2 3]
 [4 5 6]
 [7 8 9]]
new array after adding new column: [[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]]


In [14]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("arry after deleting element at index 2:",deleted)



arry after deleting element at index 2: [1 2 4 5]


In [18]:
number=np.array([1,2,3,4,5])
odd_number=number[number%2!=0]
print("odd numbers in the array:",odd_number)
mask=number>2
print("boolean mask for numbers greater than 2:",mask)
print("number greater than 2:",number[mask])

odd numbers in the array: [1 3 5]
boolean mask for numbers greater than 2: [False False  True  True  True]
number greater than 2: [3 4 5]


## indexing slicing vs npwhere


In [20]:
indices=[1,3,4]
print(number[indices])
where_with=np.where(number>2)
print("indices of numbers greater than 2:",where_with)
print("numbers greater than 2 using where:",number[where_with])



[2 4 5]
indices of numbers greater than 2: (array([2, 3, 4]),)
numbers greater than 2 using where: [3 4 5]


In [21]:
conditional=np.where(number%2==0,"even","odd")
print("conditional array with even and odd:",conditional)
print("original array remains unchanged:",number)

conditional array with even and odd: ['odd' 'even' 'odd' 'even' 'odd']
original array remains unchanged: [1 2 3 4 5]
