### we are learnig numpy basic
with the channel cup and chai

In [3]:
import numpy as np


### create array from the list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [7]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n", arr_2d)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



### array vs list

In [9]:
py_list=[1,2,3,4,5]
print("multiplication of list with 5:",py_list*5)
np_arr=np.array(py_list)
print("multiplication of array with 5:",np_arr*5)

multiplication of list with 5: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
multiplication of array with 5: [ 5 10 15 20 25]


In [10]:
import time

In [11]:
start=time.time()
py_list=[i*3 for i in range(1000000)]
end=time.time()
print("the time taken by list function is:",end-start)
start=time.time()
np_arr=np.arange(1000000)*3
end=time.time()
print("the time taken by array function is:",end-start)

the time taken by list function is: 0.2389845848083496
the time taken by array function is: 0.029554128646850586


### array from the scratch 

In [ ]:
zeros=np.zeros((3,4))
ones=np.ones((2,5))
print("zeros array :\n",zeros)
print("ones array :\n",ones)
sequence=np.arange(0,10,2)
print("sequence array:\n",sequence)
full=np.full((3,3),7)
print("full array:\n",full)
random=np.random.random((2,3))
print("random array:\n",random)

zeros array :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
sequence array:
 [0 2 4 6 8]
full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
random array:
 [[0.62779551 0.68660093 0.70630627]
 [0.93983667 0.6944172  0.2164554 ]]


### vector matices tensor

In [ ]:
vector=np.array([1,2,3])
print("vector:\n",vector)
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix:\n",matrix)
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print("tensor:\n",tensor)

vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## array properties


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("print the shape of arr:",arr.shape)
print("print the number of dimensions of arr:",arr.ndim)
print("print the data type of arr:",arr.dtype)
print("print the size of each element in bytes:",arr.itemsize)  
print("print the size of array:",arr.size)

print the shape of arr: (3, 3)
print the number of dimensions of arr: 2
print the data type of arr: int64
print the size of each element in bytes: 8
print the size of array: 9


### reshaping of array

In [17]:
arr_1d=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D array:\n", arr_1d)
reshaped_arr=arr_1d.reshape(5,2)
print("reshaped_arr:",reshaped_arr)
flattend=reshaped_arr.flatten()
print("\n flattened array:",flattend)
raveled=reshaped_arr.ravel()
print("raveled array:",raveled)
transpose=reshaped_arr.T
print("transpose of reshaped_arr:\n",transpose)

1D array:
 [ 1  2  3  4  5  6  7  8  9 10]
reshaped_arr: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

 flattened array: [ 1  2  3  4  5  6  7  8  9 10]
raveled array: [ 1  2  3  4  5  6  7  8  9 10]
transpose of reshaped_arr:
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


## sorting of numpy array

In [2]:
unsorted =np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("sorted array:",np.sort(unsorted))
unsorted_2d=np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print("sorted 2D array :",np.sort(unsorted_2d,axis=0))
print("sorted 2D array along rows:",np.sort(unsorted_2d,axis=1))

NameError: name 'np' is not defined

In [3]:
import numpy as n